name: course_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/vectors/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PublicSans-Black.ttf
        - asset: assets/font/PublicSans-BlackItalic.ttf
        - asset: assets/font/PublicSans-Bold.ttf
        - asset: assets/font/PublicSans-BoldItalic.ttf
        - asset: assets/font/PublicSans-ExtraBold.ttf
        - asset: assets/font/PublicSans-ExtraBoldItalic.ttf
        - asset: assets/font/PublicSans-ExtraLight.ttf
        - asset: assets/font/PublicSans-ExtraLightItalic.ttf
        - asset: assets/font/PublicSans-Italic.ttf
        - asset: assets/font/PublicSans-Light.ttf
        - asset: assets/font/PublicSans-LightItalic.ttf
        - asset: assets/font/PublicSans-Medium.ttf
        - asset: assets/font/PublicSans-MediumItalic.ttf
        - asset: assets/font/PublicSans-Regular.ttf
        - asset: assets/font/PublicSans-SemiBold.ttf
        - asset: assets/font/PublicSans-SemiBoldItalic.ttf
        - asset: assets/font/PublicSans-Thin.ttf
        - asset: assets/font/PublicSans-ThinItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
